// Downloads self-hosted fonts (Playfair Display + Inter) from Google Fonts.
// Self-hosting avoids third-party requests -> better performance/Privacy.
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = process.cwd();
const FONT_DIR = join(ROOT, 'assets', 'fonts');
const CSS_DIR = join(ROOT, 'assets', 'css');
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const families =
  'family=Playfair+Display:wght@500;600;700&family=Inter:wght@400;500;600;700';
const url = `https://fonts.googleapis.com/css2?${families}&display=swap`;

const res = await fetch(url, { headers: { 'user-agent': UA } });
if (!res.ok) throw new Error('Font CSS request failed: ' + res.status);
const css = await res.text();

const blocks = css.split(/(?=@font-face)/);
const latin = [];
for (const b of blocks) {
  if (!b.includes('/* latin */')) continue;
  const family = (b.match(/font-family: '([^']+)'/) || [])[1];
  const weight = (b.match(/font-weight: (\d+)/) || [])[1];
  const style = (b.match(/font-style: ([^;]+)/) || [])[1] || 'normal';
  const urlMatch = b.match(/url\((https:[^)]+)\)/);
  const uni = (b.match(/unicode-range: ([^;]+)/) || [])[1] || '';
  if (!family || !weight || !urlMatch) continue;
  latin.push({ family, weight, style, url: urlMatch[1], uni });
}

if (!latin.length) throw new Error('No latin font blocks found');

await mkdir(FONT_DIR, { recursive: true });
await mkdir(CSS_DIR, { recursive: true });

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-');

let out = '/* Auto-generated by scripts/fetch-fonts.mjs - self-hosted fonts */\n';
for (const f of latin) {
  const file = `${slug(f.family)}-${f.weight}-${f.style === 'italic' ? 'i' : ''}.woff2`;
  const buf = Buffer.from(await (await fetch(f.url)).arrayBuffer());
  await writeFile(join(FONT_DIR, file), buf);
  out += `@font-face{font-family:'${f.family}';font-style:${f.style};font-weight:${f.weight};font-display:swap;src:url(../fonts/${file}) format('woff2');unicode-range:${f.uni}}\n`;
  console.log(`saved ${file} (${(buf.length / 1024).toFixed(0)} KB)`);
}

await writeFile(join(CSS_DIR, 'fonts.css'), out);
console.log(`fonts.css written (${latin.length} faces)`);